# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - .stack-work

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev
  postgresql: "9.6"

services:
  - postgresql

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies

before_script:
  - psql -c 'create database herxheim2018_test;' -U postgres

script:
# Build the package, its tests, and its docs and run the tests
  - env DATABASE_URL='postgres://postgres@localhost/herxheim2018_test' stack --no-terminal test --haddock --no-haddock-deps
